In [1]:
import numpy as np
import tensorflow as tf

### Membuat random tensor flow dengan shape 5:5

In [2]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)>

### Membuat prime tensor list bilangan prima dengan shape 5:5

In [3]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], 
shape=[5, 5], dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

### Aritmatika penjumlahan

In [4]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[  1.1886818   4.4845986   5.0653296   4.557296   11.099248 ]
 [ 13.591225   17.592823   16.877071   22.277103   28.94373  ]
 [ 31.643545   36.735676   42.856632   43.56784    46.617165 ]
 [ 51.514656   60.261772   60.974693   70.73537    74.532814 ]
 [ 77.25702    82.5621     88.43399    97.32067   102.13283  ]], shape=(5, 5), dtype=float32)


### Aritmatika perkalian

In [5]:

print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  -1.6226364     4.4537964     0.32664686  -17.09893       1.0917324 ]
 [   7.685916     10.077991    -40.335663    -16.626637     -1.6318411 ]
 [  19.949888     -9.77999      76.12196      24.417194    -17.993286  ]
 [ -78.7232       74.444496     -1.5436709   -18.788708    111.89541   ]
 [-137.69519     -36.345116    -50.37489      31.10492     114.41593   ]], shape=(5, 5), dtype=float32)


### Aritmatika pangkat

In [6]:

print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[ 6.58237278e-01  3.27210546e+00  1.18998764e-06 -5.18914917e+02
   9.20362137e-12]
 [ 1.07839960e-03  1.37951167e-04 -1.62845650e+06 -5.73800469e-04
  -5.72948387e-37]
 [ 1.16397109e-06 -4.15966456e-22  1.04176673e+11  2.70254808e-11
  -2.52112615e-20]
 [-1.27886054e+09  9.07514625e+05 -0.00000000e+00 -0.00000000e+00
   3.47317018e+13]
 [-1.15356923e+19 -1.71214119e-30 -1.00310215e-22  0.00000000e+00
   2.95581156e+05]], shape=(5, 5), dtype=float32)


### Aritmatika pembagian

In [7]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[-4.0565911e-01  4.9486625e-01  1.3065875e-02 -3.4895775e-01
   9.0225823e-03]
 [ 4.5478795e-02  3.4871940e-02 -1.1173314e-01 -3.1430315e-02
  -1.9403580e-03]
 [ 2.0759510e-02 -7.1438937e-03  4.5283735e-02  1.3205621e-02
  -8.1454450e-03]
 [-2.8025346e-02  2.1385951e-02 -4.1485377e-04 -3.7271788e-03
   2.0997450e-02]
 [-2.2063002e-02 -5.2758185e-03 -6.3596629e-03  3.3058687e-03
   1.1216149e-02]], shape=(5, 5), dtype=float32)


### Aritmatika logaritma

In [8]:

print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[        nan  0.39514455 -2.7283134          nan -2.3101294 ]
 [-0.5255598  -0.52285945         nan         nan         nan]
 [-0.44076362         nan  0.61876476 -0.5659126          nan]
 [        nan  0.23251635         nan         nan  0.42710513]
 [        nan         nan         nan -1.1373451   0.12471979]], shape=(5, 5), dtype=float32)


### Nilai maks random tensor

In [9]:
argmax_random = tf.random.normal([5,5])
print("Nilai random_tensor",argmax_random.numpy())

max_random_1 = tf.argmax(argmax_random, axis = 0)
max_random_2 = tf.argmax(argmax_random, axis = 1)

print("Nilai maksimal berdasarkan kolom:",max_random_1.numpy())
print("Nilai maksimal berdasarkan baris:",max_random_2.numpy())

Nilai random_tensor [[-0.9535285  -0.6628795   2.6050966   0.97283906 -0.61676574]
 [-0.30219504 -1.3578846   1.2704016  -0.7363761   1.1506319 ]
 [-0.46638396 -0.91073775  0.21086329  0.22197883  1.2660271 ]
 [ 1.4899206  -0.9719209   0.16760662  0.08416482  0.8064228 ]
 [ 1.4544802  -0.27840063  1.4453667   1.0109597  -0.494657  ]]
Nilai maksimal berdasarkan kolom: [3 4 0 4 2]
Nilai maksimal berdasarkan baris: [2 2 4 0 0]


### Nilai min random tensor

In [10]:
argmin_random = tf.random.normal([5,5])
print("Nilai random_tensor",argmax_random.numpy())

min_random_1 = tf.argmin(argmin_random, axis = 0)
min_random_2 = tf.argmin(argmin_random, axis = 1)

print("Nilai minimum berdasarkan kolom:",min_random_1.numpy())
print("Nilai minimum berdasarkan baris:",min_random_2.numpy())

Nilai random_tensor [[-0.9535285  -0.6628795   2.6050966   0.97283906 -0.61676574]
 [-0.30219504 -1.3578846   1.2704016  -0.7363761   1.1506319 ]
 [-0.46638396 -0.91073775  0.21086329  0.22197883  1.2660271 ]
 [ 1.4899206  -0.9719209   0.16760662  0.08416482  0.8064228 ]
 [ 1.4544802  -0.27840063  1.4453667   1.0109597  -0.494657  ]]
Nilai minimum berdasarkan kolom: [1 0 3 3 1]
Nilai minimum berdasarkan baris: [0 4 0 3 3]


### Menggabungkan random_tensor dan prime_tensor

In [11]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], 
shape=[5, 5], dtype=tf.float32)

print("Original size data:",random_tensor.shape,prime_tensor.shape)
concated_tensor = tf.concat([random_tensor,prime_tensor],axis=0)
print("Penggabungan size data:",concated_tensor.shape)

Original size data: (5, 5) (5, 5)
Penggabungan size data: (10, 5)


### Sorting

In [12]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
print("Data random tensor",random_tensor.numpy())
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], 
shape=[5, 5], dtype=tf.float32)
print("Data prime tensor",prime_tensor.numpy())

sorted_random = tf.sort(random_tensor, direction = "DESCENDING")
print("Sorted random tensor by descending order\n",sorted_random.numpy())
sorted_prime = tf.sort(prime_tensor, direction = "DESCENDING")
print("Sorted prime tensor by descending order\n",sorted_prime.numpy())

Data random tensor [[-0.28433853  0.8922832   0.8983451   0.7163981   0.34969485]
 [-0.37960768  0.01531979  0.27423722 -2.214901   -0.08514621]
 [ 1.0113182   0.6616626   1.383323   -0.40465203  0.86142987]
 [-0.12589967 -1.418615    2.0295074   0.15304402  0.13658497]
 [-0.49787143  0.38847125 -0.4244715   0.46214256 -0.5444318 ]]
Data prime tensor [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]
Sorted random tensor by descending order
 [[ 0.8983451   0.8922832   0.7163981   0.34969485 -0.28433853]
 [ 0.27423722  0.01531979 -0.08514621 -0.37960768 -2.214901  ]
 [ 1.383323    1.0113182   0.86142987  0.6616626  -0.40465203]
 [ 2.0295074   0.15304402  0.13658497 -0.12589967 -1.418615  ]
 [ 0.46214256  0.38847125 -0.4244715  -0.49787143 -0.5444318 ]]
Sorted prime tensor by descending order
 [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  